spring:
  application:
    name: petfriends-almoxarifado

  datasource:
    url: jdbc:h2:mem:almoxarifadodb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      bindings:
        receberPedidoCriado-in-0:
          destination: pedido-criado
          group: almoxarifado-group
        pedidoDespachado-out-0:
          destination: pedido-despachado

      gcp:
        pubsub:
          binder:
            project-id: petfriends-project
        credentials:
          location: classpath:gcp-credentials.json

server:
  port: 8082
